spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bk?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 100000MB
mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.dxc.blog.pojo
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: false
  params: countSql
  page-size-zero: true
upload:
  path: C:\\Users\\dxc\\Desktop\\
server:
  port: 8088
logging:
  level:
    com.dxc.blog.dao: debug